from pydantic import BaseModel, Field
from typing import Literal, Optional


class PlatformDailyReport(BaseModel):
    """Defines the data structure for daily platform operational reports, used as input for LLM decision-making."""
    day: int = Field(description="The current date.")
    current_theta: float = Field(description="The current moderation threshold of the platform.")

    regulatory_cost: float = Field(description="Regulatory costs/fine risks generated due to missed AI content reports.")
    regulatory_cost_severity: str = Field(description="Severity rating of regulatory costs.")

    total_churn_cost: float = Field(description="User churn cost (total), a core indicator reflecting community health.")
    explicit_churn_cost: float = Field(description="Explicit cost generated by actual user churn events today.")
    potential_churn_cost: float = Field(description="Potential community dissatisfaction cost generated by cumulative false positives (FP), a key early warning signal.")
    churn_cost_severity: str = Field(description="Severity rating of total user churn cost.")

    fp_today: int = Field(description="Number of new false positives (FP) today.")
    grievance_total: float = Field(description="Currently accumulated community dissatisfaction value.")

    net_pressure: float = Field(description="Net pressure. Positive values lean towards tightening, negative values lean towards loosening.")
    system_recommendation: float = Field(description="The new threshold recommended by the algorithm based on current data.")


class PlatformDecision(BaseModel):
    """Defines the final decision of the platform agent, as LLM output."""
    new_theta: Optional[float] = Field(
        ge=0.05, le=0.95,
        description="This field must contain the new threshold (0.05-0.95)."
    )
    reason: str = Field(
        min_length=20,
        description="Detailed and well-thought-out reason for making this decision, at least 20 characters."
    )
