from typing import List

import yaml
from pathlib import Path

from pydantic import BaseModel, Field, SecretStr, ConfigDict
from pydantic_settings import BaseSettings, SettingsConfigDict

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent


class PlatformSettings(BaseModel):
    """Platform's dynamic game and strategy adjustment related parameters"""
    tau_tech: float = Field(
        ge=0,
        description="The platform's detector level. The higher the value, the higher the accuracy."
    )
    steep: float = Field(
        ge=0,
        description="Pressure sensitivity adjustment factor: determines the steepness of the tanh curve, i.e., the platform's sensitivity to pressure."
    )
    eta: float = Field(
        ge=0,
        description="Strategy adjustment rate: determines the maximum magnitude of each adjustment step."
    )
    mu: float = Field(
        ge=0,
        description="Base influence unit price: monetizes abstract 'influence' and compares it with regulatory costs."
    )
    w: float = Field(
        ge=0,
        description="User churn aversion coefficient: >1 means afraid of user churn, <1 means afraid of government punishment."
    )
    simple_run_days: int = Field(
        ge=0,
        description="Simplified framework operation days."
    )
    complete_run_days: int = Field(
        ge=0,
        description="Complete framework operation days."
    )
    simple_batch_size: int = Field(
        ge=0,
        description="In the simplified framework, the quantity processed in one batch."
    )
    dissatisfaction_per_fp: float = Field(
        ge=0,
        description="Dissatisfaction points generated by each false positive."
    )
    dissatisfaction_decay_rate: float = Field(
        ge=0,
        description="Daily dissatisfaction decay rate (5% of dissatisfaction will be 'forgotten')."
    )
    dissatisfaction_to_churn_cost_factor: float = Field(
        ge=0,
        description="Factor for converting accumulated dissatisfaction value into potential user churn cost."
    )
    post_wish_threshold: float = Field(
        ge=-10,
        description="When the agent's satisfaction with the platform is lower than this threshold, it no longer wants to post content."
    )
    is_active_threshold: float = Field(
        ge=-10,
        description="When the agent's satisfaction with the platform is lower than this threshold, it leaves the platform."
    )
    import_policy_day_time: int = Field(
        ge=-1,
        description="The start time for importing policies."
    )
    kpi_window_size: int = Field(
        ge=-1,
        description="KPI window size."
    )
    case_validation: bool = Field(
        default=False,
        description="Whether to enable case validation"
    )
    efficiency_validation: bool = Field(
        default=False,
        description="Whether to enable efficiency validation"
    )
    ablation_validation: bool = Field(
        default=False,
        description="Whether to enable ablation validation"
    )


class PublicAgentSettings(BaseModel):
    """Public agent behavior parameters"""
    number_of_interactions: int = Field(
        gt=0,
        description="After the agent browses content, if the number of interactions reaches this limit, it ends browsing."
    )
    number_of_compressions: int = Field(
        gt=0,
        description="In the agent ReAct process, when messages accumulate to this number, message compression is triggered."
    )
    number_of_keep: int = Field(
        gt=0,
        description="In the agent react process, the number of messages kept after message compression"
    )


class FileLoadPathSettings(BaseModel):
    """Loading paths for all external files"""
    contents_file: str = Field(description="Content file path")
    watermark_file: str = Field(description="Watermarking technology knowledge base file path")
    personas_file: str = Field(description="Agent persona file path")
    token_file: str = Field(description="CSV file path used to store Token consumption records")
    chroma_db_file: str = Field(description="Storage directory for Chroma vector database")
    daily_memory_exports_file: str = Field(description="Storage directory for daily exported memories")


class NsgeSettings(BaseModel):
    """NSGA algorithm parameters"""
    population_size: int = Field(description="NSGA algorithm initial population size")
    generations: int = Field(description="NSGA iteration rounds")


class ModelSettings(BaseModel):
    """LLM model names used for different tasks"""
    public_scan_model: str = Field(description="Content browsing model")
    public_summarize_model: str = Field(description="Content summarization model")
    creator_model: str = Field(description="Creator driving model")
    platform_model: str = Field(description="Platform driving model")
    compression_memory_model: str = Field(description="Message compression model")
    simple_model: str = Field(description="Model driven by the simplified simulation framework")
    dialogue_history_model: str = Field(description="Dialogue history summarization model")


class LLMKeySettings(BaseModel):
    """LLM model keys"""
    qwen: str = Field(description="Which qwen key to select for use")
    single_key_concurrency_num: int = Field(description="Single key concurrency number")


class LLMSettings(BaseModel):
    """Store sensitive API keys"""
    # Use SecretStr to protect keys, avoiding leakage in logs or printing
    model_config = ConfigDict(extra='allow')


class AppSettings(BaseSettings):
    """
    Overall project configuration model.
    It will first load structured data from a YAML file,
    then automatically find and override sensitive information like LLM keys from .env files or environment variables.
    """
    # Configure Pydantic-settings behavior
    model_config = SettingsConfigDict(
        env_file='.env',  # Specify the .env file name to load
        env_file_encoding='utf-8',  # .env file encoding
        env_nested_delimiter='__',  # Nested environment variable delimiter (e.g., LLM__KEY1)
        extra='ignore'  # Ignore redundant variables in .env
    )

    # Combine all sub-models
    platform: PlatformSettings
    public_agent: PublicAgentSettings
    nsga: NsgeSettings
    file_load_path: FileLoadPathSettings
    model: ModelSettings
    llm: LLMSettings
    llm_key: LLMKeySettings


def load_settings(config_path: str | Path) -> AppSettings:
    """
    Load configuration from the specified YAML configuration file path.

    Args:
        config_path: Path to the YAML configuration file.

    Returns:
        A fully validated and populated AppSettings instance.
    """
    with open(config_path, 'r', encoding='utf-8') as f:
        config_data = yaml.safe_load(f)

    # Use model_validate method to create an instance
    # Pydantic-settings will automatically handle loading of .env and environment variables
    return AppSettings.model_validate(config_data)


if __name__ == '__main__':
    settings = load_settings("config.yaml")
    print('2')