platform:
  tau_tech: 0.75  # 平台的检测器水平。值越高，准确度越高。
  steep: 6  # (压力敏感度调节因子):它决定了`tanh`曲线的陡峭程度，即平台对压力的“敏感度”。
  eta: 0.1  # 决定了每一步调整的最大幅度。
  mu: 5  # 基础影响力单价。负责将抽象的“影响力点数”货币化，使其能与监管成本在同一维度上进行比较。
  w: 1.0  # 平台的用户流失厌恶系数 >1:怕用户流失。 <1:怕政府惩罚

  kpi_window_size: 3  # KPI窗口大小
  import_policy_day_time: 3  # 导入策略的开始时间。

  dissatisfaction_per_fp: 1.0  # 每一次误报产生的不满点数
#  dissatisfaction_decay_rate: 0.2  # 每日不满值的保留率-》低粒度
  dissatisfaction_decay_rate: 0.8  # 每日不满值的保留率-》高粒度
  dissatisfaction_to_churn_cost_factor: 1  # 将累积不满值转化为潜在用户流失成本的因子

  simple_batch_size: 3  # 简化框架中，一次批量处理的数量

  simple_run_days: 15  # 简化框架运行天数。
  complete_run_days: 15  # 完整框架运行天数。

  post_wish_threshold: -1.6  # 当智能体对平台的满意度低于这个阈值，就不想再发布内容/高于这个阈值，就开始发布内容
  is_active_threshold: -1.8  # 当智能体对平台的满意度低于这个阈值，就脱离平台

  case_validation: False  # 是否开启案例验证
  efficiency_validation: False  # 是否开启效率验证
  ablation_validation: False  # 是否开启消融验证



nsga:
  population_size: 10  # nsga算法初始种群大小
  generations: 1  # nsga迭代轮数

public_agent:
  number_of_interactions: 4  # 智能体在浏览内容后，互动的次数达到这个限制，就结束浏览。
  number_of_compressions: 5  # 智能体react流程中，消息累积到这个数量，就触发消息压缩
  number_of_keep: 4  # 智能体react流程中，消息压缩后，保留消息的数量

file_load_path:
  contents_file: "method/data/contents.json"  # 内容文件
  watermark_file: "method/data/watermarking_technology_to_combat_databases-2.json"  # 水印文件
#  personas_file: "method/data/test_persona.json"  # 人群文件
#  personas_file: "method/data/scenario_protest.json"
  personas_file: "method/data/personas_30.json"
#  personas_file: "method/data/low_beta_personas_30.json"
#  personas_file: "method/data/high_beta_personas_30.json"
#  personas_file: "method/data/personas_100.json"
  token_file: "method/store/token/all_token.csv"  # 用于存储运行中消耗的token数量
  chroma_db_file: "method/store/chroma_db"  # 用于存储chroma数据库的目录
  daily_memory_exports_file: "method/store/daily_memory_exports"  # 用于存储每日导出的记忆的目录

model:
  public_scan_model: "qwen-flash"  # 浏览内容模型
  public_summarize_model: "qwen-plus"  # 总结内容模型
  creator_model: "qwen-plus"  # 创作者驱动模型
  platform_model: "qwen-plus"  # 平台模型
  compression_memory_model: "qwen-flash"  # 消息压缩模型
  simple_model: "qwen-flash"  # 简化框架驱动的模型
  dialogue_history_model: "qwen-flash"  # 对话历史总结模型

llm_key:
  qwen: "key1"  # 选择哪个key
  single_key_concurrency_num: 3  # 单key并发数